# settings commons to all profiles


# actuator properties
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,beans,mappings
  endpoint:
    health:
      show-details: always