# settings commons to all profiles


# server properties
server:
  port: 8081

# actuator properties
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,beans,mappings
  endpoint:
    health:
      show-details: always