# settings commons to all profiles


# server properties
server:
  port: 8081


# jpa / hibernate config

spring :
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create-drop


# actuator properties
management:
  endpoints:
    web:
      exposure:
        include: "*"
        #include: health,info,metrics,loggers,beans,mappings
  endpoint:
    health:
      show-details: always