
# server properties
server:
  port: 8081

#h2 database properties
spring :
  jpa:
    show-sql: true
    properties:
        hibernate:
          format_sql=true:
  datasource :
    url: "jdbc:h2:mem:dbcv"
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
