
# server properties
server:
  port: 8081

#h2 database properties
spring :
  datasource :
    url: jdbc:h2:mem:dbcv
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

# actuator properties
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,beans,mappings
  endpoint:
    health:
      show-details: always