# production server properties
server:
  port: ${PORT:5000}

#postgres database properties
spring :
  jpa:
    show-sql: false
  datasource :
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    maxActive : 10
    maxIdle : 5
    minIdle : 2
    initialSize : 5
    removeAbandoned : true